# substitutions:
#   _NAME_1: $PROJECT_ID 

steps:
- name: 'gcr.io/cloud-builders/git'
  secretEnv: ['SSH_KEY']
  entrypoint: 'bash'
  args:
  - -c
  - |
    echo "$$SSH_KEY" >> /root/.ssh/id_rsa
    chmod 400 /root/.ssh/id_rsa
    cp known_hosts.github /root/.ssh/known_hosts
    echo "Following is the git version"
    git --version
    ls /root/
  volumes:
  - name: 'ssh'
    path: /root/.ssh

- name: 'gcr.io/cloud-builders/git'
  id: Deploy
  entrypoint: 'bash'
  args:
  - -c
  - |
    source package.sh
    echo "deploying code in cluster"
    kpt version
    kpt pkg init cc-files/
    kpt cfg create-setter cc-files/ name dravidq --field="metadata.name"
    cp -r cc-files hydrated-cc
    echo "Git remote"
    git remote -v
    git remote set-url origin git@github.com:MACHANDRA11/config-connector.git
    git config --global user.name "MACHANDRA11"
    git config --global user.email "chandrakanth.maddana@mediaagility.com"
    git add .
    git commit -m "applied changes"
    git push -u origin main
    # kpt cfg set cc-files/  name smtrfds
    # kpt live init cc-files/
    # kpt live apply cc-files/ -n test-cc
    # kpt live status cc-files/ -n test-cc
    # gcloud container clusters get-credentials test-config-connector --zone us-central1-a --project devtools-317213
    # kubectl apply -f hydrated-cc/ -n test-cc
  volumes:
  - name: 'ssh'
    path: /root/.ssh

availableSecrets:
  secretManager:
  - versionName: projects/$PROJECT_ID/secrets/git-secret-key/versions/latest
    env: 'SSH_KEY'

  # env:
  # - 'CLOUDSDK_COMPUTE_ZONE=us-central1-a'
  # - 'CLOUDSDK_CONTAINER_CLUSTER=test-config-connector'

# - name: 'gcr.io/cloud-builders/kubectl'
#   id: Deploy
#   args:
#   - 'apply'
#   - '-f'
#   - 'cc-files/bg1.yaml'
#   - '-n'
#   - 'test-cc'
#   env:
#   - 'CLOUDSDK_COMPUTE_ZONE=us-central1-a'
#   - 'CLOUDSDK_CONTAINER_CLUSTER=test-config-connector'

# steps:
# - name: 'gcr.io/cloud-builders/git'
#   secretEnv: ['SSH_KEY']
#   entrypoint: 'bash'
#   args:
#   - -c
#   - |
#     echo "$$SSH_KEY" >> /root/.ssh/id_rsa
#     chmod 400 /root/.ssh/id_rsa
#     cp known_hosts.github /root/.ssh/known_hosts
#   volumes:
#   - name: 'ssh'
#     path: /root/.ssh


  # This step builds the container image.
# - name: 'gcr.io/cloud-builders/docker'
#   id: Build
#   args:
#   - 'build'
#   - '-t'
#   - 'gcr.io/$PROJECT_ID/test_cha:8'
#   - '.'

# This step pushes the image to Container Registry
# The PROJECT_ID and SHORT_SHA variables are automatically
# replaced by Cloud Build.
# - name: 'gcr.io/cloud-builders/docker'
#   id: Push
#   args:
#   - 'push'
#   - 'gcr.io/$PROJECT_ID/test_cha:8'

# images: ['gcr.io/$PROJECT_ID/test_cha:8']